In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('football.csv')

In [3]:
data

,sofifa_id,short_name,overall,potential,value_eur,wage_eur,age,height_cm,weight_kg,club_team_id,...,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,goalkeeping_speed,contribution_type
0,158023,L. Messi,93,93,78000000.0,320000.0,34,170,72,73.0,...,20,35,24,6,11,15,14,8,NaN,1
1,188545,R. Lewandowski,92,92,119500000.0,270000.0,32,185,81,21.0,...,35,42,19,15,6,12,8,10,NaN,1
2,20801,Cristiano Ronaldo,91,91,45000000.0,270000.0,36,187,83,11.0,...,24,32,24,7,11,15,14,11,NaN,1
3,190871,Neymar Jr,91,91,129000000.0,270000.0,29,175,68,73.0,...,35,32,29,9,9,15,15,11,NaN,1
4,192985,K. De Bruyne,91,91,125500000.0,350000.0,30,181,70,10.0,...,68,65,53,15,13,5,10,13,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7767,260174,S. Ghosh,51,64,140000.0,500.0,20,174,70,111629.0,...,15,23,25,15,10,8,15,5,NaN,1
7768,232286,K. Chambers,50,53,60000.0,500.0,25,179,70,1586.0,...,40,45,42,12,10,14,13,15,NaN,0
7769,253657,Lan Jingxuan,50,60,100000.0,1000.0,21,175,65,111774.0,...,51,52,53,7,10,6,10,7,NaN,0
7770,258964,Zhang Jinliang,49,55,70000.0,2000.0,22,184,77,112429.0,...,51,52,53,15,13,13,12,6,NaN,0
7771,260474,Kim Bong Soo,48,57,100000.0,800.0,21,183,78,1478.0,...,41,47,54,13,10,14,15,13,NaN,1

In [4]:
data.head()

,sofifa_id,short_name,overall,potential,value_eur,wage_eur,age,height_cm,weight_kg,club_team_id,...,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,goalkeeping_speed,contribution_type
0,158023,L. Messi,93,93,78000000.0,320000.0,34,170,72,73.0,...,20,35,24,6,11,15,14,8,NaN,1
1,188545,R. Lewandowski,92,92,119500000.0,270000.0,32,185,81,21.0,...,35,42,19,15,6,12,8,10,NaN,1
2,20801,Cristiano Ronaldo,91,91,45000000.0,270000.0,36,187,83,11.0,...,24,32,24,7,11,15,14,11,NaN,1
3,190871,Neymar Jr,91,91,129000000.0,270000.0,29,175,68,73.0,...,35,32,29,9,9,15,15,11,NaN,1
4,192985,K. De Bruyne,91,91,125500000.0,350000.0,30,181,70,10.0,...,68,65,53,15,13,5,10,13,NaN,1

In [6]:
data[(data['short_name']=='L. Messi') | (data['short_name']=='R. Lewandowski') | (data['short_name']=='Cristiano Ronaldo') | (data['short_name']=='Neymar Jr')]['league_name']

0            French Ligue 1
1      German 1. Bundesliga
2    English Premier League
3            French Ligue 1
Name: league_name, dtype: object

In [61]:
df = data[(data['league_name']=='French Ligue 1') | (data['league_name']=='German 1. Bundesliga') | (data['league_name']=='English Premier League')]

In [90]:
df['sofifa_id'].duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
5805    False
5872    False
5919    False
6997    False
7106    False
Name: sofifa_id, Length: 638, dtype: bool

In [63]:
df.isnull().sum()

sofifa_id                    0
short_name                   0
overall                      0
potential                    0
value_eur                    0
                          ...
goalkeeping_kicking          0
goalkeeping_positioning      0
goalkeeping_reflexes         0
goalkeeping_speed          580
contribution_type            0
Length: 66, dtype: int64

In [64]:
col = []
for i,j in enumerate(df.isnull().sum()):
    if j!=0:
        col.append(i)

In [65]:
s = df.isnull().sum()

In [66]:
s.index[col]

Index(['nation_jersey_number', 'release_clause_eur', 'player_tags',
       'player_traits', 'pace', 'shooting', 'passing', 'dribbling',
       'defending', 'physic', 'goalkeeping_speed'],
      dtype='object')

In [67]:
df[s.index[col]]

,nation_jersey_number,release_clause_eur,player_tags,player_traits,pace,shooting,passing,dribbling,defending,physic,goalkeeping_speed
0,10.0,144300000.0,"#Dribbler, #Distance Shooter, #FK Specialist, ...","Finesse Shot, Long Shot Taker (AI), Playmaker ...",85.0,92.0,91.0,95.0,34.0,65.0,NaN
1,9.0,197200000.0,"#Aerial Threat, #Distance Shooter, #Clinical F...","Solid Player, Finesse Shot, Outside Foot Shot,...",78.0,92.0,79.0,86.0,44.0,82.0,NaN
2,7.0,83300000.0,"#Aerial Threat, #Dribbler, #Distance Shooter, ...","Power Free-Kick, Flair, Long Shot Taker (AI), ...",87.0,94.0,80.0,88.0,34.0,75.0,NaN
3,NaN,238700000.0,"#Speedster, #Dribbler, #Playmaker, #FK Special...","Injury Prone, Flair, Speed Dribbler (AI), Play...",91.0,83.0,86.0,94.0,37.0,63.0,NaN
4,7.0,232200000.0,"#Dribbler, #Playmaker, #Engine, #Distance Shoo...","Injury Prone, Leadership, Early Crosser, Long ...",76.0,86.0,93.0,88.0,64.0,78.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
5805,NaN,4500000.0,NaN,NaN,60.0,40.0,57.0,51.0,66.0,72.0,NaN
5872,NaN,3500000.0,NaN,Long Shot Taker (AI),63.0,58.0,61.0,68.0,60.0,66.0,NaN
5919,NaN,3000000.0,NaN,NaN,65.0,48.0,62.0,62.0,62.0,66.0,NaN
6997,NaN,2300000.0,NaN,NaN,79.0,31.0,56.0,63.0,54.0,68.0,NaN
7106,NaN,2500000.0,NaN,NaN,79.0,46.0,56.0,58.0,56.0,58.0,NaN

In [68]:
df.columns

Index(['sofifa_id', 'short_name', 'overall', 'potential', 'value_eur',
       'wage_eur', 'age', 'height_cm', 'weight_kg', 'club_team_id',
       'club_name', 'league_name', 'league_level', 'club_jersey_number',
       'nation_jersey_number', 'preferred_foot', 'weak_foot', 'skill_moves',
       'international_reputation', 'work_rate', 'body_type',
       'release_clause_eur', 'player_tags', 'player_traits', 'pace',
       'shooting', 'passing', 'dribbling', 'defending', 'physic',
       'attacking_crossing', 'attacking_finishing',
       'attacking_heading_accuracy', 'attacking_short_passing',
       'attacking_volleys', 'skill_dribbling', 'skill_curve',
       'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control',
       'movement_acceleration', 'movement_sprint_speed', 'movement_agility',
       'movement_reactions', 'movement_balance', 'power_shot_power',
       'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots',
       'mentality_aggression', 'mentality_interceptions',
       'mentality_positioning', 'mentality_vision', 'mentality_penalties',
       'mentality_composure', 'defending_marking_awareness',
       'defending_standing_tackle', 'defending_sliding_tackle',
       'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking',
       'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed',
       'contribution_type'],
      dtype='object')

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 638 entries, 0 to 7106
Data columns (total 66 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   sofifa_id                    638 non-null    int64
 1   short_name                   638 non-null    object
 2   overall                      638 non-null    int64
 3   potential                    638 non-null    int64
 4   value_eur                    638 non-null    float64
 5   wage_eur                     638 non-null    float64
 6   age                          638 non-null    int64
 7   height_cm                    638 non-null    int64
 8   weight_kg                    638 non-null    int64
 9   club_team_id                 638 non-null    float64
 10  club_name                    638 non-null    object
 11  league_name                  638 non-null    object
 12  league_level                 638 non-null    float64
 13  club_jersey_number           638 non-null    float64
 14  nation_jersey_number         142 non-null    float64
 15  preferred_foot               638 non-null    object
 16  weak_foot                    638 non-null    int64
 17  skill_moves                  638 non-null    int64
 18  international_reputation     638 non-null    int64
 19  work_rate                    638 non-null    object
 20  body_type                    638 non-null    object
 21  release_clause_eur           606 non-null    float64
 22  player_tags                  164 non-null    object
 23  player_traits                515 non-null    object
 24  pace                         580 non-null    float64
 25  shooting                     580 non-null    float64
 26  passing                      580 non-null    float64
 27  dribbling                    580 non-null    float64
 28  defending                    580 non-null    float64
 29  physic                       580 non-null    float64
 30  attacking_crossing           638 non-null    int64
 31  attacking_finishing          638 non-null    int64
 32  attacking_heading_accuracy   638 non-null    int64
 33  attacking_short_passing      638 non-null    int64
 34  attacking_volleys            638 non-null    int64
 35  skill_dribbling              638 non-null    int64
 36  skill_curve                  638 non-null    int64
 37  skill_fk_accuracy            638 non-null    int64
 38  skill_long_passing           638 non-null    int64
 39  skill_ball_control           638 non-null    int64
 40  movement_acceleration        638 non-null    int64
 41  movement_sprint_speed        638 non-null    int64
 42  movement_agility             638 non-null    int64
 43  movement_reactions           638 non-null    int64
 44  movement_balance             638 non-null    int64
 45  power_shot_power             638 non-null    int64
 46  power_jumping                638 non-null    int64
 47  power_stamina                638 non-null    int64
 48  power_strength               638 non-null    int64
 49  power_long_shots             638 non-null    int64
 50  mentality_aggression         638 non-null    int64
 51  mentality_interceptions      638 non-null    int64
 52  mentality_positioning        638 non-null    int64
 53  mentality_vision             638 non-null    int64
 54  mentality_penalties          638 non-null    int64
 55  mentality_composure          638 non-null    int64
 56  defending_marking_awareness  638 non-null    int64
 57  defending_standing_tackle    638 non-null    int64
 58  defending_sliding_tackle     638 non-null    int64
 59  goalkeeping_diving           638 non-null    int64
 60  goalkeeping_handling         638 non-null    int64
 61  goalkeeping_kicking          638 non-null    int64
 62  goalkeeping_positioning      638 non-null    int64
 63  goalkeeping_reflexes         638 non-null    int64
 64  goalkeeping_speed            58 non-null     float64
 65  contribution_type            638 non-null    int64
dtypes: float64(14), int64(44), object(8)
memory usage: 334.0+ KB

In [96]:
remove_col = ['nation_jersey_number','player_tags','player_traits','sofifa_id','short_name','value_eur','club_team_id','league_level','club_jersey_number','preferred_foot','weak_foot','release_clause_eur','body_type','work_rate']

In [97]:
df.shape

(638, 66)

In [98]:
og = df.drop(remove_col,axis=1)

In [99]:
og.info()

<class 'pandas.core.frame.DataFrame'>
Index: 638 entries, 0 to 7106
Data columns (total 52 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   overall                      638 non-null    int64
 1   potential                    638 non-null    int64
 2   wage_eur                     638 non-null    float64
 3   age                          638 non-null    int64
 4   height_cm                    638 non-null    int64
 5   weight_kg                    638 non-null    int64
 6   club_name                    638 non-null    object
 7   league_name                  638 non-null    object
 8   skill_moves                  638 non-null    int64
 9   international_reputation     638 non-null    int64
 10  pace                         580 non-null    float64
 11  shooting                     580 non-null    float64
 12  passing                      580 non-null    float64
 13  dribbling                    580 non-null    float64
 14  defending                    580 non-null    float64
 15  physic                       580 non-null    float64
 16  attacking_crossing           638 non-null    int64
 17  attacking_finishing          638 non-null    int64
 18  attacking_heading_accuracy   638 non-null    int64
 19  attacking_short_passing      638 non-null    int64
 20  attacking_volleys            638 non-null    int64
 21  skill_dribbling              638 non-null    int64
 22  skill_curve                  638 non-null    int64
 23  skill_fk_accuracy            638 non-null    int64
 24  skill_long_passing           638 non-null    int64
 25  skill_ball_control           638 non-null    int64
 26  movement_acceleration        638 non-null    int64
 27  movement_sprint_speed        638 non-null    int64
 28  movement_agility             638 non-null    int64
 29  movement_reactions           638 non-null    int64
 30  movement_balance             638 non-null    int64
 31  power_shot_power             638 non-null    int64
 32  power_jumping                638 non-null    int64
 33  power_stamina                638 non-null    int64
 34  power_strength               638 non-null    int64
 35  power_long_shots             638 non-null    int64
 36  mentality_aggression         638 non-null    int64
 37  mentality_interceptions      638 non-null    int64
 38  mentality_positioning        638 non-null    int64
 39  mentality_vision             638 non-null    int64
 40  mentality_penalties          638 non-null    int64
 41  mentality_composure          638 non-null    int64
 42  defending_marking_awareness  638 non-null    int64
 43  defending_standing_tackle    638 non-null    int64
 44  defending_sliding_tackle     638 non-null    int64
 45  goalkeeping_diving           638 non-null    int64
 46  goalkeeping_handling         638 non-null    int64
 47  goalkeeping_kicking          638 non-null    int64
 48  goalkeeping_positioning      638 non-null    int64
 49  goalkeeping_reflexes         638 non-null    int64
 50  goalkeeping_speed            58 non-null     float64
 51  contribution_type            638 non-null    int64
dtypes: float64(8), int64(42), object(2)
memory usage: 264.2+ KB

In [100]:
og.shape

(638, 52)

In [103]:
og['league_name'].value_counts()

league_name
French Ligue 1            220
English Premier League    220
German 1. Bundesliga      198
Name: count, dtype: int64

In [102]:
og['club_name'].value_counts()

club_name
Paris Saint-Germain         11
RC Strasbourg Alsace        11
FC Girondins de Bordeaux    11
FC Augsburg                 11
Newcastle United            11
Sport-Club Freiburg         11
Stade Rennais FC            11
Brighton & Hove Albion      11
Hertha BSC                  11
FC Metz                     11
Watford                     11
Racing Club de Lens         11
DSC Arminia Bielefeld       11
1. FC Köln                  11
Angers SCO                  11
FC Bayern München           11
FC Nantes                   11
VfB Stuttgart               11
Stade de Reims              11
Norwich City                11
Stade Brestois 29           11
AS Saint-Étienne            11
Brentford                   11
1. FSV Mainz 05             11
FC Lorient                  11
VfL Bochum 1848             11
ESTAC Troyes                11
SpVgg Greuther Fürth        11
OGC Nice                    11
Montpellier Hérault SC      11
Southampton                 11
1. FC Union Berlin          11
Manchester United           11
Manchester City             11
Tottenham Hotspur           11
Chelsea                     11
Liverpool                   11
Borussia Dortmund           11
VfL Wolfsburg               11
Leicester City              11
Borussia Mönchengladbach    11
RB Leipzig                  11
Arsenal                     11
AS Monaco                   11
Everton                     11
Aston Villa                 11
Eintracht Frankfurt         11
Bayer 04 Leverkusen         11
Burnley                     11
Wolverhampton Wanderers     11
TSG Hoffenheim              11
West Ham United             11
Crystal Palace              11
Olympique Lyonnais          11
Leeds United                11
LOSC Lille                  11
Olympique de Marseille      11
Clermont Foot 63            11
Name: count, dtype: int64

In [82]:
from sklearn.impute import KNNImputer

In [184]:
imputer = KNNImputer(n_neighbors=10)

In [185]:
imputed_data = imputer.fit_transform(og.drop(['club_name','league_name'],axis=1))

In [186]:
imputed_data[0]

array([9.30e+01, 9.30e+01, 3.20e+05, 3.40e+01, 1.70e+02, 7.20e+01,
       4.00e+00, 5.00e+00, 8.50e+01, 9.20e+01, 9.10e+01, 9.50e+01,
       3.40e+01, 6.50e+01, 8.50e+01, 9.50e+01, 7.00e+01, 9.10e+01,
       8.80e+01, 9.60e+01, 9.30e+01, 9.40e+01, 9.10e+01, 9.60e+01,
       9.10e+01, 8.00e+01, 9.10e+01, 9.40e+01, 9.50e+01, 8.60e+01,
       6.80e+01, 7.20e+01, 6.90e+01, 9.40e+01, 4.40e+01, 4.00e+01,
       9.30e+01, 9.50e+01, 7.50e+01, 9.60e+01, 2.00e+01, 3.50e+01,
       2.40e+01, 6.00e+00, 1.10e+01, 1.50e+01, 1.40e+01, 8.00e+00,
       5.11e+01, 1.00e+00])

In [187]:
og_cols = ['overall', 'potential', 'wage_eur', 'age', 'height_cm', 'weight_kg',
        'skill_moves', 'international_reputation',
       'pace', 'shooting', 'passing', 'dribbling', 'defending', 'physic',
       'attacking_crossing', 'attacking_finishing',
       'attacking_heading_accuracy', 'attacking_short_passing',
       'attacking_volleys', 'skill_dribbling', 'skill_curve',
       'skill_fk_accuracy', 'skill_long_passing', 'skill_ball_control',
       'movement_acceleration', 'movement_sprint_speed', 'movement_agility',
       'movement_reactions', 'movement_balance', 'power_shot_power',
       'power_jumping', 'power_stamina', 'power_strength', 'power_long_shots',
       'mentality_aggression', 'mentality_interceptions',
       'mentality_positioning', 'mentality_vision', 'mentality_penalties',
       'mentality_composure', 'defending_marking_awareness',
       'defending_standing_tackle', 'defending_sliding_tackle',
       'goalkeeping_diving', 'goalkeeping_handling', 'goalkeeping_kicking',
       'goalkeeping_positioning', 'goalkeeping_reflexes', 'goalkeeping_speed',
       'contribution_type']

In [188]:
imputed_df = pd.DataFrame(imputed_data,columns=og_cols)

In [189]:
og = og.reset_index(drop=True)

In [190]:
og.head()

,overall,potential,wage_eur,age,height_cm,weight_kg,club_name,league_name,skill_moves,international_reputation,...,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,goalkeeping_speed,contribution_type
0,93,93,320000.0,34,170,72,Paris Saint-Germain,French Ligue 1,4,5,...,20,35,24,6,11,15,14,8,NaN,1
1,92,92,270000.0,32,185,81,FC Bayern München,German 1. Bundesliga,4,5,...,35,42,19,15,6,12,8,10,NaN,1
2,91,91,270000.0,36,187,83,Manchester United,English Premier League,5,5,...,24,32,24,7,11,15,14,11,NaN,1
3,91,91,270000.0,29,175,68,Paris Saint-Germain,French Ligue 1,5,5,...,35,32,29,9,9,15,15,11,NaN,1
4,91,91,350000.0,30,181,70,Manchester City,English Premier League,4,4,...,68,65,53,15,13,5,10,13,NaN,1

In [191]:
imputed_df.head(5)

,overall,potential,wage_eur,age,height_cm,weight_kg,skill_moves,international_reputation,pace,shooting,...,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,goalkeeping_speed,contribution_type
0,93.0,93.0,320000.0,34.0,170.0,72.0,4.0,5.0,85.0,92.0,...,20.0,35.0,24.0,6.0,11.0,15.0,14.0,8.0,51.1,1.0
1,92.0,92.0,270000.0,32.0,185.0,81.0,4.0,5.0,78.0,92.0,...,35.0,42.0,19.0,15.0,6.0,12.0,8.0,10.0,51.1,1.0
2,91.0,91.0,270000.0,36.0,187.0,83.0,5.0,5.0,87.0,94.0,...,24.0,32.0,24.0,7.0,11.0,15.0,14.0,11.0,51.1,1.0
3,91.0,91.0,270000.0,29.0,175.0,68.0,5.0,5.0,91.0,83.0,...,35.0,32.0,29.0,9.0,9.0,15.0,15.0,11.0,51.1,1.0
4,91.0,91.0,350000.0,30.0,181.0,70.0,4.0,4.0,76.0,86.0,...,68.0,65.0,53.0,15.0,13.0,5.0,10.0,13.0,51.1,1.0

In [192]:
imputed_df['league_name'] = og['league_name']
imputed_df['club_name'] = og['club_name']

In [193]:

imputed_df.shape

(638, 52)

In [194]:
og.shape

(638, 52)

In [195]:
ind = np.random.randint(0,638)

In [196]:
imputed_df.iloc[ind,:]

overall                                          76.0
potential                                        80.0
wage_eur                                      46000.0
age                                              25.0
height_cm                                       187.0
weight_kg                                        70.0
skill_moves                                       3.0
international_reputation                          1.0
pace                                             80.0
shooting                                         75.0
passing                                          58.0
dribbling                                        72.0
defending                                        46.0
physic                                           80.0
attacking_crossing                               52.0
attacking_finishing                              80.0
attacking_heading_accuracy                       78.0
attacking_short_passing                          62.0
attacking_volleys                                76.0
skill_dribbling                                  68.0
skill_curve                                      61.0
skill_fk_accuracy                                56.0
skill_long_passing                               54.0
skill_ball_control                               72.0
movement_acceleration                            80.0
movement_sprint_speed                            80.0
movement_agility                                 82.0
movement_reactions                               77.0
movement_balance                                 70.0
power_shot_power                                 71.0
power_jumping                                    89.0
power_stamina                                    78.0
power_strength                                   81.0
power_long_shots                                 65.0
mentality_aggression                             78.0
mentality_interceptions                          49.0
mentality_positioning                            79.0
mentality_vision                                 62.0
mentality_penalties                              80.0
mentality_composure                              77.0
defending_marking_awareness                      35.0
defending_standing_tackle                        46.0
defending_sliding_tackle                         41.0
goalkeeping_diving                               16.0
goalkeeping_handling                              8.0
goalkeeping_kicking                               8.0
goalkeeping_positioning                           7.0
goalkeeping_reflexes                              8.0
goalkeeping_speed                                45.5
contribution_type                                 1.0
league_name                    English Premier League
club_name                                   Brentford
Name: 341, dtype: object

In [197]:
og.iloc[ind,:]

overall                                            76
potential                                          80
wage_eur                                      46000.0
age                                                25
height_cm                                         187
weight_kg                                          70
club_name                                   Brentford
league_name                    English Premier League
skill_moves                                         3
international_reputation                            1
pace                                             80.0
shooting                                         75.0
passing                                          58.0
dribbling                                        72.0
defending                                        46.0
physic                                           80.0
attacking_crossing                                 52
attacking_finishing                                80
attacking_heading_accuracy                         78
attacking_short_passing                            62
attacking_volleys                                  76
skill_dribbling                                    68
skill_curve                                        61
skill_fk_accuracy                                  56
skill_long_passing                                 54
skill_ball_control                                 72
movement_acceleration                              80
movement_sprint_speed                              80
movement_agility                                   82
movement_reactions                                 77
movement_balance                                   70
power_shot_power                                   71
power_jumping                                      89
power_stamina                                      78
power_strength                                     81
power_long_shots                                   65
mentality_aggression                               78
mentality_interceptions                            49
mentality_positioning                              79
mentality_vision                                   62
mentality_penalties                                80
mentality_composure                                77
defending_marking_awareness                        35
defending_standing_tackle                          46
defending_sliding_tackle                           41
goalkeeping_diving                                 16
goalkeeping_handling                                8
goalkeeping_kicking                                 8
goalkeeping_positioning                             7
goalkeeping_reflexes                                8
goalkeeping_speed                                 NaN
contribution_type                                   1
Name: 341, dtype: object

In [198]:
imputed_df.to_csv('imputed_data.csv',index=False)

In [199]:
imputed_df.isnull().sum()

overall                        0
potential                      0
wage_eur                       0
age                            0
height_cm                      0
weight_kg                      0
skill_moves                    0
international_reputation       0
pace                           0
shooting                       0
passing                        0
dribbling                      0
defending                      0
physic                         0
attacking_crossing             0
attacking_finishing            0
attacking_heading_accuracy     0
attacking_short_passing        0
attacking_volleys              0
skill_dribbling                0
skill_curve                    0
skill_fk_accuracy              0
skill_long_passing             0
skill_ball_control             0
movement_acceleration          0
movement_sprint_speed          0
movement_agility               0
movement_reactions             0
movement_balance               0
power_shot_power               0
power_jumping                  0
power_stamina                  0
power_strength                 0
power_long_shots               0
mentality_aggression           0
mentality_interceptions        0
mentality_positioning          0
mentality_vision               0
mentality_penalties            0
mentality_composure            0
defending_marking_awareness    0
defending_standing_tackle      0
defending_sliding_tackle       0
goalkeeping_diving             0
goalkeeping_handling           0
goalkeeping_kicking            0
goalkeeping_positioning        0
goalkeeping_reflexes           0
goalkeeping_speed              0
contribution_type              0
league_name                    0
club_name                      0
dtype: int64

In [200]:
def return_cols(text):
    col = []
    for i in imputed_df.columns:
        if text in set(i.split('_')):
            col.append(i)
    return col

In [201]:
return_cols('attacking')

['attacking_crossing',
 'attacking_finishing',
 'attacking_heading_accuracy',
 'attacking_short_passing',
 'attacking_volleys']

In [202]:
attack = return_cols('attacking')

In [203]:
attack

['attacking_crossing',
 'attacking_finishing',
 'attacking_heading_accuracy',
 'attacking_short_passing',
 'attacking_volleys']

In [204]:
imputed_df[attack].describe()

,attacking_crossing,attacking_finishing,attacking_heading_accuracy,attacking_short_passing,attacking_volleys
count,638.000000,638.000000,638.000000,638.000000,638.000000
mean,59.818182,53.669279,60.570533,70.506270,50.634796
std,19.668641,21.658373,18.579049,12.985046,20.465382
min,9.000000,5.000000,10.000000,20.000000,5.000000
25%,50.000000,38.000000,53.000000,68.000000,34.000000
50%,66.000000,58.000000,65.000000,73.000000,54.000000
75%,74.000000,71.000000,74.000000,78.000000,68.000000
max,94.000000,95.000000,92.000000,94.000000,89.000000

In [205]:
skill = return_cols('skill')

In [206]:
skill

['skill_moves',
 'skill_dribbling',
 'skill_curve',
 'skill_fk_accuracy',
 'skill_long_passing',
 'skill_ball_control']

In [218]:
skill.remove('skill_moves')

In [219]:
skill

['skill_dribbling',
 'skill_curve',
 'skill_fk_accuracy',
 'skill_long_passing',
 'skill_ball_control']

In [220]:
imputed_df[skill].describe()

,skill_dribbling,skill_curve,skill_fk_accuracy,skill_long_passing,skill_ball_control
count,638.000000,638.000000,638.000000,638.000000,638.000000
mean,66.468652,57.645768,49.940439,64.774295,70.065831
std,19.166497,20.038971,19.554205,13.914264,15.763421
min,8.000000,9.000000,8.000000,12.000000,10.000000
25%,62.250000,46.000000,36.000000,59.000000,68.000000
50%,72.000000,62.000000,51.000000,68.000000,74.000000
75%,78.000000,74.000000,66.000000,74.000000,79.000000
max,96.000000,93.000000,94.000000,93.000000,96.000000

In [221]:
power = return_cols('power')

In [222]:
power

['power_shot_power',
 'power_jumping',
 'power_stamina',
 'power_strength',
 'power_long_shots']

In [223]:
imputed_df[power].describe()

,power_shot_power,power_jumping,power_stamina,power_strength,power_long_shots
count,638.000000,638.00000,638.000000,638.000000,638.000000
mean,68.034483,70.34326,71.498433,71.152038,56.023511
std,12.344050,11.81595,14.805887,10.740718,20.609117
min,23.000000,32.00000,20.000000,31.000000,7.000000
25%,59.000000,64.00000,67.000000,65.000000,43.000000
50%,71.000000,71.00000,75.000000,72.000000,63.000000
75%,77.000000,78.00000,80.750000,78.000000,72.000000
max,94.000000,95.00000,97.000000,95.000000,94.000000

In [224]:
mentality = return_cols('mentality')
defending = return_cols('defending')
goalkeeping = return_cols('goalkeeping')

In [225]:
mentality

['mentality_aggression',
 'mentality_interceptions',
 'mentality_positioning',
 'mentality_vision',
 'mentality_penalties',
 'mentality_composure']

In [226]:
defending

['defending',
 'defending_marking_awareness',
 'defending_standing_tackle',
 'defending_sliding_tackle']

In [227]:
goalkeeping

['goalkeeping_diving',
 'goalkeeping_handling',
 'goalkeeping_kicking',
 'goalkeeping_positioning',
 'goalkeeping_reflexes',
 'goalkeeping_speed']

In [228]:
imputed_df[mentality].describe()

,mentality_aggression,mentality_interceptions,mentality_positioning,mentality_vision,mentality_penalties,mentality_composure
count,638.000000,638.000000,638.00000,638.000000,638.000000,638.000000
mean,66.036050,58.133229,59.50627,65.145768,53.717868,70.882445
std,16.710677,22.198819,21.44049,13.395531,16.925046,10.501714
min,16.000000,7.000000,4.00000,18.000000,11.000000,23.000000
25%,59.000000,38.000000,48.00000,57.000000,43.000000,66.000000
50%,70.000000,68.000000,67.00000,68.000000,54.000000,72.000000
75%,78.000000,76.000000,75.00000,75.000000,66.000000,77.000000
max,93.000000,91.000000,96.00000,95.000000,93.000000,96.000000

In [229]:
imputed_df[defending].describe()

,defending,defending_marking_awareness,defending_standing_tackle,defending_sliding_tackle
count,638.000000,638.000000,638.000000,638.000000
mean,62.441693,57.608150,58.728840,55.412226
std,16.620061,22.017691,23.181696,23.196877
min,19.000000,9.000000,10.000000,8.000000
25%,49.000000,38.000000,38.000000,34.000000
50%,68.400000,68.000000,70.000000,67.000000
75%,75.000000,75.000000,76.000000,74.000000
max,91.000000,92.000000,93.000000,92.000000

In [230]:
imputed_df[goalkeeping].describe()

,goalkeeping_diving,goalkeeping_handling,goalkeeping_kicking,goalkeeping_positioning,goalkeeping_reflexes,goalkeeping_speed
count,638.000000,638.000000,638.000000,638.000000,638.000000,638.000000
mean,16.583072,16.409091,16.221003,16.340125,17.053292,45.911599
std,20.029299,19.192662,18.462650,19.625904,20.580973,4.138799
min,5.000000,3.000000,2.000000,4.000000,3.000000,25.000000
25%,8.000000,8.000000,8.000000,8.000000,8.000000,43.300000
50%,11.000000,11.000000,11.000000,11.000000,11.000000,45.400000
75%,14.000000,14.000000,14.000000,14.000000,14.000000,48.400000
max,91.000000,88.000000,93.000000,90.000000,90.000000,65.000000

In [236]:
movement = return_cols('movement')

In [237]:
movement

['movement_acceleration',
 'movement_sprint_speed',
 'movement_agility',
 'movement_reactions',
 'movement_balance']

In [238]:
imputed_df[movement].describe()

,movement_acceleration,movement_sprint_speed,movement_agility,movement_reactions,movement_balance
count,638.000000,638.000000,638.000000,638.000000,638.000000
mean,68.573668,69.106583,68.189655,74.769592,66.434169
std,14.338695,14.519556,14.369319,6.824686,15.047426
min,26.000000,18.000000,21.000000,51.000000,24.000000
25%,61.000000,62.000000,60.000000,71.000000,57.000000
50%,70.000000,71.000000,70.000000,75.000000,68.000000
75%,78.000000,79.000000,78.000000,79.000000,77.000000
max,97.000000,97.000000,96.000000,94.000000,95.000000

In [239]:
imputed_df['attacking'] = imputed_df[attack].mean(axis=1)
imputed_df['skill'] = imputed_df[skill].mean(axis=1)
imputed_df['movement'] = imputed_df[movement].mean(axis=1)
imputed_df['power'] = imputed_df[power].mean(axis=1)
imputed_df['mentality'] = imputed_df[mentality].mean(axis=1)
imputed_df['defending'] = imputed_df[defending].mean(axis=1)
imputed_df['goalkeeping'] = imputed_df[goalkeeping].mean(axis=1)

In [241]:
mod_df = imputed_df.drop(attack+skill+movement+power+mentality+defending+goalkeeping+['skill_moves'],axis=1)

In [308]:
ind = np.random.randint(1,638)

In [309]:
mod_df.loc[ind]

overall                                     77.0
potential                                   82.0
wage_eur                                 18000.0
age                                         23.0
height_cm                                  190.0
weight_kg                                   88.0
international_reputation                     1.0
pace                                        72.7
shooting                                    49.8
passing                                     59.2
dribbling                                   64.2
physic                                      71.7
contribution_type                            0.0
league_name                 German 1. Bundesliga
club_name                          VfB Stuttgart
attacking                                   15.2
skill                                       19.0
power                                       45.0
mentality                              25.666667
goalkeeping                            69.833333
movement                                    48.8
Name: 301, dtype: object

In [310]:
og.loc[ind]

overall                                          77
potential                                        82
wage_eur                                    18000.0
age                                              23
height_cm                                       190
weight_kg                                        88
club_name                             VfB Stuttgart
league_name                    German 1. Bundesliga
skill_moves                                       1
international_reputation                          1
pace                                            NaN
shooting                                        NaN
passing                                         NaN
dribbling                                       NaN
defending                                       NaN
physic                                          NaN
attacking_crossing                               12
attacking_finishing                              11
attacking_heading_accuracy                       11
attacking_short_passing                          32
attacking_volleys                                10
skill_dribbling                                  18
skill_curve                                      13
skill_fk_accuracy                                12
skill_long_passing                               28
skill_ball_control                               24
movement_acceleration                            43
movement_sprint_speed                            43
movement_agility                                 42
movement_reactions                               75
movement_balance                                 41
power_shot_power                                 54
power_jumping                                    58
power_stamina                                    34
power_strength                                   67
power_long_shots                                 12
mentality_aggression                             25
mentality_interceptions                          19
mentality_positioning                            11
mentality_vision                                 42
mentality_penalties                              19
mentality_composure                              38
defending_marking_awareness                      20
defending_standing_tackle                        11
defending_sliding_tackle                         12
goalkeeping_diving                               76
goalkeeping_handling                             74
goalkeeping_kicking                              72
goalkeeping_positioning                          73
goalkeeping_reflexes                             81
goalkeeping_speed                              43.0
contribution_type                                 0
Name: 301, dtype: object

In [254]:
mod_df.to_csv('final_data.csv',index=False)

In [256]:
mod_df.shape

(638, 21)

In [311]:
data[(data['goalkeeping_diving']==76) & (data['goalkeeping_handling']==74) & (data['goalkeeping_kicking']==72)   & (data['goalkeeping_positioning']==73) & (data['goalkeeping_reflexes']==81)  & (data['goalkeeping_speed']==43.0)][['short_name','league_name','club_name']]

    short_name           league_name      club_name
762  F. Müller  German 1. Bundesliga  VfB Stuttgart